name: Validity

on:
  push:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    strategy:
      matrix:
        node-version: [18.18.2]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
